---
title: On Demand Training
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  main-header:
    title: main_header
    output: true
defaults:
- scope:
    path: ''
  values:
    lang: en
domain: services.github.com
author: GitHub, Inc.
email: services@github.com
locale: en-US
title_separator: "-"
name: GitHub, Inc.
description: You're in control. We're with you along the way.
baseurl: 
gh_repo: 
teaser: 
breadcrumbs: true
words_per_minute: 200
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
analytics:
  provider: google
  google:
    tracking_id: UA-3769691-2
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
parentsite: https://services.github.com
permalink: "/articles/:title/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
include:
- _stylesheets
- _javascript
sass:
  load_paths:
  - assets/_scss
  - node_modules
  style: compressed
lang: en
